motor_calibrator:
  # Node params
  node_frequency: 0.5 # [Hz]

  # calibrator params
  max_turns: 2.0
  turns_trial: 20

  # Sleep time for robot dynamics
  sleep_time: 10.0  #[s] (ahimè)

  current_data_skip: 30  # discard samples
  mean_sample: 20
